version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  springboot:
    build: .
    container_name: springboot
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/test
    depends_on:
      - mongodb
